version: '3'
services:
  backend:
    build:
      context: ./api/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend/app
    ports:
      - "3000:3000"
  db:
    image: postgres
    volumes:
      - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: database
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080   